// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzsp6ZAomqhEYSml8d9LB3ELwdVfLKn20',
    appId: '1:882441758013:web:8b07df1821e09a9ecb9154',
    messagingSenderId: '882441758013',
    projectId: 'pu-connection-797f2',
    authDomain: 'pu-connection-797f2.firebaseapp.com',
    storageBucket: 'pu-connection-797f2.firebasestorage.app',
    measurementId: 'G-WJCJWN5PT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl90uWao7_2E_z9kQyD7Uq1QoBNF9cy7M',
    appId: '1:882441758013:android:6e246296fc4d02cdcb9154',
    messagingSenderId: '882441758013',
    projectId: 'pu-connection-797f2',
    storageBucket: 'pu-connection-797f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsogZjpCImOe21EmqpgEQwjtEpZ21Aatg',
    appId: '1:882441758013:ios:2e9da9a5d638a599cb9154',
    messagingSenderId: '882441758013',
    projectId: 'pu-connection-797f2',
    storageBucket: 'pu-connection-797f2.firebasestorage.app',
    iosBundleId: 'com.example.puConnection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsogZjpCImOe21EmqpgEQwjtEpZ21Aatg',
    appId: '1:882441758013:ios:2e9da9a5d638a599cb9154',
    messagingSenderId: '882441758013',
    projectId: 'pu-connection-797f2',
    storageBucket: 'pu-connection-797f2.firebasestorage.app',
    iosBundleId: 'com.example.puConnection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzsp6ZAomqhEYSml8d9LB3ELwdVfLKn20',
    appId: '1:882441758013:web:e7a1feb8a9ee4642cb9154',
    messagingSenderId: '882441758013',
    projectId: 'pu-connection-797f2',
    authDomain: 'pu-connection-797f2.firebaseapp.com',
    storageBucket: 'pu-connection-797f2.firebasestorage.app',
    measurementId: 'G-TFKB4EK5RN',
  );
}
